ouster_driver:
  ros__parameters:
    # modified by zyl
    lidar_ip: 192.168.1.100
    computer_ip: 192.168.1.10
    lidar_mode: "2048x16"
    imu_port: 9866
    lidar_port: 2368
    sensor_frame: laser_sensor_frame
    laser_frame: laser_data_frame
    imu_frame: imu_data_frame

    # if False, data are published with sensor data QoS. This is preferrable
    # for production but default QoS is needed for rosbag.
    # See: https://github.com/ros2/rosbag2/issues/125
    use_system_default_qos: true

    # Set the method used to timestamp measurements.
    # Valid modes are:
    #
    #   TIME_FROM_INTERNAL_OSC
    #   TIME_FROM_SYNC_PULSE_IN
    #   TIME_FROM_PTP_1588
    #   TIME_FROM_ROS_RECEPTION
    #
    # (See this project's README and/or the Ouster Software Guide for more
    # information).
    #
    timestamp_mode: TIME_FROM_INTERNAL_OSC

    # Mask-like-string used to define the data processors that should be
    # activated upon startup of the driver. This will determine the topics
    # that are available for client applications to consume. The defacto
    # reference for these values are defined in:
    # `include/ros2_ouster/OS1/processor_factories.hpp`
    #
    # For convenience, the available data processors are:
    #
    # IMG   - Provides 8-bit image topics suitable for ML applications encoding
    #         the noise, range, intensity, and reflectivity data from a scan
    # PCL   - Provides a point cloud encoding of a LiDAR scan
    # IMU   - Provides a data stream from the LiDARs integral IMU
    # SCAN  - Provides a synthesized 2D LaserScan from the 3D LiDAR data
    #
    # To construct a valid string for this parameter join the tokens from above
    # (in any combination) with the pipe character. For example, valid strings
    # include (but are not limited to):
    #
    # IMG|PCL
    # IMG|PCL|IMU|SCAN
    # PCL
    #
    
    # os1_proc_mask: IMG|PCL|IMU|SCAN
    os1_proc_mask: SCAN
    # added by zyl for tranform
    imu_to_sensor_transform: [1.0,0.0,0.0,6.253,0.0,1.0,0.0,-11.175,0.0,0.0,1.0,7.645,0.0,0.0,0.0,1.0]
    lidar_to_sensor_transform: [-1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,1.0,36.18,0.0,0.0,0.0,1.0]
    
    # added by zyl for correct
    x_offset_array: [21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,-21.0,-21.0,-21.0,-21.0,-21.0,-21.0,-21.0,-21.0]
    y_offset_array: [5.06,-9.15,5.06,-9.15,5.06,-9.15,5.06,-9.15,9.15,-5.06,9.15,-5.06,9.15,-5.06,9.15,-5.06]
    ah_offset_array: [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
    av_offset_array: [-15.0,1.0,-13.0,3.0,-11.0,5.0,-9.0,7.0,-7.0,9.0,-5.0,11.0,-3.0,13.0,-1.0,15.0]
    laser_id_array: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    num_lasers: 16
    distance_resolution: 0.002
    ring_scan: 0
    lidar_vendor: OLE_3D_V2
    
    
    
